services:
  # ===================== SIDECARS (must come first) ====================
  service-a-daprd:
    image: "daprio/daprd:1.14.4"
    command: [
      "./daprd",
      "-app-id","orders",
      "-app-port","8001",
      "-dapr-http-port","3500",
      "-dapr-grpc-port","50001",
      "-metrics-port","9092",
      "-config","/dapr/config.yaml"
    ]
    ports:
      - "3500:3500"  # Sidecar HTTP port exposed
      - "50001:50001"  # Sidecar gRPC port exposed
      - "9092:9092"  # Sidecar metrics port exposed
    volumes:
      - ./dapr:/dapr
    depends_on: [otel-collector]

  service-b-daprd:
    image: "daprio/daprd:1.14.4"
    command: [
      "./daprd",
      "-app-id","payments",
      "-app-port","8002",
      "-dapr-http-port","3501",
      "-dapr-grpc-port","50002",
      "-metrics-port","9091",
      "-config","/dapr/config.yaml"
    ]
    ports:
      - "3501:3501"  # Sidecar HTTP port exposed
      - "50002:50002"  # Sidecar gRPC port exposed
      - "9091:9091"  # Sidecar metrics port exposed
    volumes:
      - ./dapr:/dapr
    depends_on: [otel-collector]



  # ===================== APPS (run behind sidecars) =====================
  service-a:
    build: ./services/service-a
    container_name: service-a
    network_mode: "service:service-a-daprd"
    environment:
      - DAPR_HTTP=http://localhost:3500
      - TARGET_APP_ID=payments
    depends_on: [service-a-daprd]

  service-b:
    build: ./services/service-b
    container_name: service-b
    network_mode: "service:service-b-daprd"
    environment:
      - DAPR_HTTP=http://localhost:3501
    depends_on: [service-b-daprd]


  # ===================== OBSERVABILITY =====================

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel/collector.yaml"]
    ports:
      - "8889:8889"  # Spanmetrics connector metrics port
    volumes:
      - ./otel/collector.yaml:/etc/otel/collector.yaml:ro
    depends_on: [jaeger]

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    restart: unless-stopped
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [otel-collector]

  jaeger:
    image: jaegertracing/all-in-one:1.64.0
    container_name: jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NAMESPACE=spanmetrics     
      # Specific configuration for Service Performance Monitoring (SPM)  
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
      - PROMETHEUS_QUERY_LATENCY_UNIT=ms
    ports:
      - "16686:16686"